parameters:
    debril.provider.mock.class: Debril\RssAtomBundle\Provider\MockProvider
    debril.provider.default.class: Debril\RssAtomBundle\Provider\MockProvider
    debril.provider.doctrine.class: Debril\RssAtomBundle\Provider\DoctrineFeedContentProvider

services:
    guzzle.client:
        class: GuzzleHttp\Client

    feedio.client:
        class: FeedIo\Adapter\Guzzle\Client
        arguments: ["@guzzle.client"]

    feedio:
        public: true
        class: FeedIo\FeedIo
        arguments: ["@feedio.client", "@logger"]
        calls:
          - method: addDateFormats
            arguments:
              - '%debril_rss_atom.date_formats%'

    debril.provider.default:
        class: '%debril.provider.default.class%'

    debril.provider.mock:
        class: '%debril.provider.mock.class%'

    Debril\RssAtomBundle\Controller\StreamController:
        public: true
        tags:
            # add multiple tags to control multiple args
            - name: controller.service_arguments
              action: indexAction
              argument: provider
              id: debril.provider.default
            - name: controller.service_arguments
              action: indexAction
              argument: feedIo
              id: feedio
